apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-capstone
  namespace: udacity-capstone
  labels:
    app: cloud-devops-capstone
spec:
  selector:
    app: cloud-devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-deployment
  namespace: udacity-capstone
  labels:
    app: cloud-devops-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-devops-capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: cloud-devops-capstone
    spec:
      containers:
      - name: cloud-devops-capstone
        image: scavassa/cloud-devops-capstone:latest
        envFrom:
        - secretRef:
            name: helios-env
        ports:
        - containerPort: 8000