version: 2.1

orbs:
  slack: circleci/slack@4.2.1

            
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Check If Infrastructure Exists, Creates It If Doesn't
          command: |
            if [[ $(aws cloudformation --region ${AWS_DEFAULT_REGION} \
              describe-stacks --stack-name ${STACK_NAME} --output text) ]]
            then
              echo Stack Exists, nothing to do
            else
              aws cloudformation create-stack --stack-name ${STACK_NAME} \
                --region ${AWS_DEFAULT_REGION} --template-body file://infrastructure.yml \
                --capabilities CAPABILITY_NAMED_IAM --parameters \
                ParameterKey=pDBName,ParameterValue=${DB_NAME} \
                ParameterKey=pDBUser,ParameterValue=${DB_USER} \
                ParameterKey=pDBPass,ParameterValue=${DB_PASS}
              while true; do 
                if [[ $(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} \
                  --stack-name ${STACK_NAME} --query "Stacks[*].StackStatus" \
                  --output text) == CREATE_IN_PROGRESS ]]
                then
                  echo -e "EKS Cluster status : CREATE IN PROGRESS \n"
                  sleep 10
                elif [[ $(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} \
                  --stack-name ${STACK_NAME} --query "Stacks[*].StackStatus" \
                  --output text) == CREATE_COMPLETE ]]
                then
                  echo -e "EKS Cluster status : SUCCESSFULLY CREATED \n"
                  break
                fi
              done
            fi
      - run:
          name: Store RDS Instance Name
          command: |
            export RDS_ID=$(aws cloudformation --region ${AWS_DEFAULT_REGION} \
              describe-stacks --stack-name ${STACK_NAME} \
              --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue" \
              --output text)
            echo ${RDS_ID}
            export RDS_DNS=$(aws rds describe-db-instances --db-instance-identifier ${RDS_ID} \
              --query "DBInstances[0].[Endpoint.Address]" --output text)
            echo ${RDS_DNS}

            

workflows:
  default:
    jobs:
      - create-infrastructure